[package]
name = "tricti"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = []
tri-runtime = []

[dependencies]
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
pest = "2.7.15"
pest_derive = "2.7.15"
tokio = { version = "1.0", features = ["full"] }
rayon = "1.10"

[dev-dependencies]
tokio-test = "0.4"
