WHITESPACE   = _{ " " | "\t" | "\n" | "\r" | COMMENT }
COMMENT      = _{ ("#" ~ (!"\n" ~ ANY)*) | ("/*" ~ (!"*/" ~ ANY)*) }

keyword_if   = @{ "if" ~ !("_"|ASCII_ALPHANUMERIC) }
keyword_else = @{ "else" ~ !("_"|ASCII_ALPHANUMERIC) }
keyword_break = @{ "break" ~ !("_"|ASCII_ALPHANUMERIC) }
keyword_continue = @{ "cont" ~ !("_"|ASCII_ALPHANUMERIC) }
reserved_keyword = _{ keyword_if | keyword_else | keyword_break | keyword_continue }
identifier   = @{ !reserved_keyword ~ ("_" | ASCII_ALPHA) ~ ("_" | ASCII_ALPHANUMERIC)* }
int_body     = { ASCII_DIGIT+ ~ ("_" ~ ASCII_DIGIT+)* }
integer      = @{ int_body ~ int_suffix? }
int_suffix   = _{ "i8" | "i16" | "i32" | "i64" | "i128" | "u8" | "u16" | "u32" | "u64" | "u128" }
float        = @{
    int_body ~ "." ~ int_body ~ float_exponent? ~ float_suffix?
    | int_body ~ "." ~ float_exponent ~ float_suffix?
    | int_body ~ float_exponent ~ float_suffix?
}
float_exponent = _{ ("e" | "E") ~ ("+" | "-")? ~ int_body }
float_suffix = _{ "f32" | "f64" }
number       = { float | integer }
string       = @{ "r"? ~ ("\"\"\"" ~ (!"\"\"\"" ~ ANY)* ~ "\"\"\"") | ("#\"" ~ (!"\"#" ~ (ANY | "\\#"))* ~ "#\"") | ("\"" ~ (!"\"" ~ !"\n" ~ (ANY | "\\\""))* ~ "\"") }
boolean      = @{ ("true" | "false") ~ !("_" | ASCII_ALPHANUMERIC) }

program      = { SOI ~ WHITESPACE* ~ statement* ~ EOI }
statement    = {
    WHITESPACE* ~ (
        const_statement
        | (simple_statement ~ ";"?)
    ) ~ WHITESPACE*
}
simple_statement = _{
    use_statement
    | mod_decl
    | variable_decl
    | assignment
    | impl_block
    | for_loop
    | return_statement
    | break_statement
    | continue_statement
    | ifdef_statement
    | conditional
    | enum
    | struct
    | trait_type
    | expression
}

const_statement = { const_decl ~ (";" ~ WHITESPACE*)? }

use_statement = { ("pub" ~ "use" | "use") ~ identifier ~ ("::" ~ (identifier | "*"))* ~ use_alias? ~ ";"? }
use_alias = { "as" ~ identifier }
mod_decl = { ("pub" ~ "mod" | "mod") ~ identifier ~ (";" | ("{" ~ statement* ~ "}")) }
return_statement = { "ret" ~ WHITESPACE* ~ expression? }
break_statement = { "break" ~ WHITESPACE* ~ expression? }
continue_statement = { "cont" }
ifdef_statement = { "@ifdef" ~ "(" ~ expression ~ ")" ~ block ~ ("@else" ~ block)? }
impl_block    = { "impl" ~ type_params? ~ type ~ ("for" ~ type)? ~ "{" ~ impl_methods ~ "}" }
impl_method   = { attributes? ~ identifier ~ "::" ~ type_params? ~ "(" ~ function_params? ~ ")" ~ return_type? ~ "=>" ~ function_body }
impl_methods  = _{ ((impl_method | const_decl) ~ ","?)* }
block = { "{" ~ WHITESPACE* ~ statement* ~ (expression ~ ";"?)? ~ WHITESPACE* ~ "}" }
unsafe_block = { "unsafe" ~ block }

for_loop     = { "for" ~ WHITESPACE* ~ identifier ~ (WHITESPACE* ~ ":" ~ WHITESPACE* ~ type)? ~ WHITESPACE* ~ "in" ~ WHITESPACE* ~ expression ~ WHITESPACE* ~ block }
loop         = { "loop" ~ WHITESPACE* ~ block }
conditional  = { keyword_if ~ WHITESPACE* ~ expression_no_block ~ &(WHITESPACE* ~ "{") ~ WHITESPACE* ~ block ~ (WHITESPACE* ~ keyword_else ~ WHITESPACE* ~ (block | conditional))? }
inline_conditional = {
    keyword_if ~ WHITESPACE* ~ expression_no_block ~ WHITESPACE* ~ (
        "then" ~ WHITESPACE* ~ expression ~ (WHITESPACE* ~ keyword_else ~ WHITESPACE* ~ expression)?
        | ":" ~ WHITESPACE* ~ expression ~ (WHITESPACE* ~ keyword_else ~ WHITESPACE* ~ expression)?
    )
}

attribute       = { "@" ~ identifier ~ ("(" ~ (expression ~ ("," ~ expression)*)? ~ ")")? }
attributes      = { attribute* }

const_decl = {
    attributes? ~
    WHITESPACE* ~
    ("extern" ~ string?)? ~
    identifier ~ type_params? ~
    (
        WHITESPACE* ~ "::" ~ WHITESPACE* ~ const_body
        | WHITESPACE* ~ ":" ~ type ~ WHITESPACE* ~ "::" ~ WHITESPACE* ~ const_body
    )
}

const_body = { attributes? ~ const_body_inner }

const_body_inner = {
            sys_def
        | compose_def
        | table_def
        | db_def
        | function
        | type_assign
        | type
        | expression
}

type_assign = { type ~ ":=" ~ expression }

sys_def = { "async"? ~ "sys" ~ "(" ~ sys_params? ~ ")" ~ return_type? ~ "=>" ~ block }
sys_params = { sys_param ~ ("," ~ sys_param)* ~ ","? }
sys_param = { attributes? ~ (query_param | resource_param | regular_param | function_param) }
query_param = { "query" ~ identifier? ~ ":" ~ query_spec }
resource_param = { identifier ~ ":" ~ "res" ~ resource_ref ~ type }
regular_param = { identifier ~ ":" ~ type ~ ("=" ~ expression)? }

query_spec = { "select" ~ field_projections ~ "from" ~ identifier ~ join_clauses? ~ ("where" ~ expression)? }
field_projections = { field_projection_group | field_projection_list }
field_projection_group = { "(" ~ field_projection_list? ~ ")" }
field_projection_list = { field_projection ~ ("," ~ field_projection)* ~ ","? }
field_projection = { identifier ~ (":" ~ resource_ref? ~ type)? }
resource_ref = { "&mut" | "&" }

join_clauses = { join_clause+ }
join_clause = { join_type ~ "join" ~ identifier ~ "on" ~ expression }
join_type = { "inner" | "left" | "right" | "full" | "" }

compose_def = { "compose" ~ "{" ~ compose_entry* ~ "}" }
compose_entry = { (identifier | tuple_chain) ~ ("->" ~ (identifier | tuple_chain))* ~ ","? }
tuple_chain = { "(" ~ identifier ~ ("," ~ identifier)* ~ ")" }

table_def = { "table" ~ "{" ~ table_fields? ~ "}" }
table_fields = { table_field ~ ("," ~ WHITESPACE* ~ table_field)* ~ ("," ~ WHITESPACE*)? }
table_field = { attribute* ~ identifier ~ ":" ~ (computed_field | (type ~ ("=" ~ expression)?)) }
computed_field = { "computed" ~ "(" ~ expression ~ ")" }

db_def = { "db" ~ "{" ~ db_entries? ~ "}" }
db_entries = { db_entry ~ ("," ~ db_entry)* ~ ","? }
db_entry = { identifier ~ (":" ~ identifier)? }

expression    = { binary_expression }
expression_no_block    = { binary_expression_no_block }

binary_expression = { unary ~ (WHITESPACE* ~ binary_operator ~ WHITESPACE* ~ unary)* }
binary_expression_no_block = { unary_no_block ~ (WHITESPACE* ~ binary_operator ~ WHITESPACE* ~ unary_no_block)* }
binary_operator = _{ op_or | op_and | op_cmp | op_shift | op_add | op_mul | op_range }
op_or         = { "or" | "xor" }
op_and        = { "and" }
op_cmp        = { "==" | "~=" | "<=" | ">=" | ">" | "<" }
op_shift      = { "<<" | ">>" }
op_add        = { "+" | "-" }
op_mul        = { "*" | ".*" | "/" | "./" | "\\" | "%" | ".%" }
op_range      = { ".." }
op_unary      = { "-" | "~" | "*" | "&mut" | "&" | "!" | "some" | "ok" | "err" | "not" }
unary         = { op_unary? ~ cast_expr }
unary_no_block = { op_unary? ~ cast_expr_no_block }
cast_expr     = { post_fix ~ (WHITESPACE* ~ cast_tail)* }
cast_expr_no_block = { post_fix_no_block ~ (WHITESPACE* ~ cast_tail)* }
cast_tail     = { "as" ~ WHITESPACE* ~ type }
static_path_suffix = { "::" ~ identifier }
field_suffix  = { "." ~ identifier }
postfix_question = { "?" ~ !ASCII_ALPHANUMERIC ~ !"*" }
postfix_bang = { "!" ~ !ASCII_ALPHANUMERIC ~ !"*" }
index_suffix = { "[" ~ (expression ~ ","?)+ ~ "]" }
post_fix      = { primary ~ (WHITESPACE* ~ (call_suffix | static_path_suffix | field_suffix | postfix_question | postfix_bang | index_suffix) )* }
post_fix_no_block = { primary_no_block ~ (WHITESPACE* ~ (call_suffix | static_path_suffix | field_suffix | postfix_question | postfix_bang | index_suffix) )* }
tuple_expr    = { "(" ~ expression ~ ("," ~ expression)+ ~ ","? ~ ")" }
primary_struct = { identifier ~ type_args ~ struct_literal | identifier ~ struct_literal }
primary       = { conditional | inline_conditional | unsafe_block | block | number | loop | match | function | literal | vec_new | vec_literal | matrix | shader | tuple_expr | path_struct | static_path | primary_struct | identifier | "(" ~ expression ~ ")" }
primary_no_block = { conditional | inline_conditional | unsafe_block | number | loop | match | function | literal_no_struct | vec_new | vec_literal | matrix | shader | tuple_expr | static_path | identifier | "(" ~ expression ~ ")" }
path_struct    = { identifier ~ ("::" ~ identifier)+ ~ struct_literal }
static_path    = { identifier ~ type_args? ~ ("::" ~ identifier)+ }

call_suffix   = { type_args ~ "(" ~ (argument ~ ("," ~ argument)* ~ ","?)? ~ ")" | "(" ~ (argument ~ ("," ~ argument)* ~ ","?)? ~ ")" }
argument      = { (identifier ~ ":")? ~ expression }
literal       = { integer | float | string | boolean | char | struct_literal }
literal_no_struct = { integer | float | string | boolean | char }

char          = @{ "'" ~ ( "\\" ~ ("'" | "\\" | "n" | "t" | "r" | "0" | "u" ~ "{" ~ ASCII_HEX_DIGIT+ ~ "}" ) | (!"\\" ~ !"'" ~ ANY) ) ~ "'" }

struct_literal = { "{" ~ (full_field | shorthand_field | ".." ~ ","?)* ~ "}" }
shorthand_field = { identifier ~ ","? }
full_field = { identifier ~ ":" ~ (unsafe_block | expression) ~ ","? }

some_ref_option_pattern = { "some" ~ WHITESPACE* ~ "ref" ~ WHITESPACE+ ~ ref_payload_pattern }
some_option_pattern = { "some" ~ WHITESPACE* ~ pattern }
none_option_pattern = { "none" }
option_pattern = { some_ref_option_pattern | some_option_pattern | none_option_pattern }
bare_identifier_pattern = { identifier ~ !(WHITESPACE* ~ "::") }
pattern_argument_list = { pattern ~ ("," ~ pattern)* ~ ","? }
enum_payload_pattern = { static_path ~ "(" ~ pattern_argument_list? ~ ")" }
tuple_pattern = { "(" ~ pattern ~ ("," ~ pattern)* ~ ","? ~ ")" }
basic_pattern = { enum_payload_pattern | tuple_pattern | literal | bare_identifier_pattern | path_struct | static_path | "_" }
ref_payload_pattern = { ref_pattern | basic_pattern }
ref_pattern   = { "ref" ~ WHITESPACE+ ~ ref_payload_pattern }
pattern       = { option_pattern | ref_pattern | basic_pattern }

match         = { "match" ~ expression ~ "{" ~ WHITESPACE* ~ match_arm ~ (WHITESPACE* ~ !"}" ~ match_arm)* ~ WHITESPACE* ~ "}" }
match_arm_pattern_text = { (!"=>" ~ ANY)+ }
match_arm     = { WHITESPACE* ~ match_arm_pattern_text ~ WHITESPACE* ~ "=>" ~ match_body ~ ("," ~ WHITESPACE*)? }
match_body    = { block | return_statement | break_statement | expression }

vec_new       = { "new" ~ "[" ~ type ~ (";" ~ expression ~ ("," ~ expression)* ~ ","?)? ~ "]" }
matrix        = { "[" ~ (row ~ ";")* ~ row ~ ";"? ~ "]" }
vec_literal   = { "[" ~ (expression ~ ("," ~ expression)* ~ ","?)? ~ "]" }
row           = { (expression ~ ","?)+ }

type_params   = { "<" ~ type_param ~ ("," ~ type_param)* ~ ">" }
type_param    = { identifier ~ trait_bounds? }
trait_bounds  = { ":" ~ type ~ ("+" ~ type)* }
type_args     = { !(" " | "\t" | "\n" | "\r") ~ "<" ~ type ~ ("," ~ type)* ~ ">" }
function      = { attributes? ~ "async"? ~ type_params? ~ "(" ~ function_params? ~ ")" ~ return_type? ~ "=>" ~ function_body }
function_params = { (function_param | variadic_param | ("self" | "&self" | "&mut self" | "*self")) ~ ("," ~ (function_param | variadic_param))* ~ ","? }
function_param = { identifier ~ (":" ~ type)? ~ ("=" ~ expression)? }
variadic_param = { "..." }
return_type   = { "->" ~ type}
function_body = { block | expression }

assignment_op = { "=" | "*=" | "/=" | "+=" | "-=" | ".*=" | "./=" | "\\=" }
assignment    = { expression ~ WHITESPACE* ~ assignment_op ~ WHITESPACE* ~ expression }
binding_pattern = { binding_tuple | "_" | identifier }
binding_tuple = { "(" ~ WHITESPACE* ~ binding_pattern ~ (WHITESPACE* ~ "," ~ WHITESPACE* ~ binding_pattern)* ~ WHITESPACE* ~ ","? ~ ")" }
variable_decl = {
    binding_pattern ~ ":" ~ !":" ~ type ~ "=" ~ expression
    | binding_pattern ~ (":" ~ type)? ~ ":=" ~ expression
}

shader        = { ("vert" | "frag" | "comp") ~ "{" ~ (const_decl | shader_field)* ~ "}" }
shader_field  = { identifier ~ ":" ~ type ~ ","? }

tuple_type    = { "(" ~ type ~ ("," ~ type)+ ~ ","? ~ ")" }
matrix_type   = { "[" ~ type ~ (";" ~ (integer | identifier ~ ","?)* )? ~ "]" }
type          = { optional | result | pointer | reference_type | base_type }
base_type     = _{ struct | enum | trait_type | matrix_type | function_type | tuple_type | "none" | identifier ~ type_args? }
reference_type = { ("&mut" | "&") ~ type }
trait_type    = { "trait" ~ "{" ~ trait_items ~ "}" }
trait_items   = _{ (trait_assoc | trait_method)* }
trait_assoc   = { identifier ~ ":" ~ "type" ~ ","? }
trait_method  = { identifier ~ ":" ~ function_type ~ ","? }

pointer       = { "&mut" ~ type | "&" ~ type | "*raw" ~ type | "*" ~ type }
optional      = { "?" ~ type }
result        = { "!" ~ type }

function_type_param = { (identifier ~ ":" ~ WHITESPACE*)? ~ type }
function_type_params = { (function_type_param | variadic_param) ~ ("," ~ WHITESPACE* ~ (function_type_param | variadic_param))* ~ ","? }
function_type = { "(" ~ WHITESPACE* ~ function_type_params? ~ ")" ~ return_type ~ !"=>" }

enum          = { "enum" ~ "{" ~ (enum_variant ~ ("," ~ enum_variant)*)? ~ ","? ~ "}" }
enum_variant = { identifier ~ (":" ~ type)? }

struct        = { "struct" ~ WHITESPACE* ~ "{" ~ struct_fields? ~ "}" }
struct_fields = _{ (identifier ~ ":" ~ type) ~ ("," ~ identifier ~ ":" ~ type)* ~ ","? }

